"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Check } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";

const stages = ["Checking image quality", "Measuring visible density", "Comparing with your baseline", "Reviewing your progress trend", "Evaluating safety signals", "Preparing your coach summary"];
export default function AnalyzingPage(){ const [active,setActive]=useState(0); const [error,setError]=useState<string|null>(null); const router=useRouter(); useEffect(()=>{ let cancelled=false; const run=async()=>{ try { const questionnaire=JSON.parse(sessionStorage.getItem("folliq-questionnaire") ?? "{}"); const response=await fetch("/api/check-ins/demo/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rawDensityRatio:0.498,baselineRatio:0.428,previousScore:112.4,treatmentWeek:21,questionnaire})}); const result=await response.json(); if(!response.ok || !result.success) throw new Error(result.error?.message ?? "Analysis failed"); for(let index=1;index<stages.length;index++){ await new Promise((resolve)=>setTimeout(resolve,380)); if(cancelled)return; setActive(index); } await new Promise((resolve)=>setTimeout(resolve,450)); sessionStorage.setItem("folliq-result",JSON.stringify(result.data)); router.replace(`/check-in/result/${result.data.analysis.id}`); } catch(err){ setError(err instanceof Error?err.message:"Analysis could not finish."); } }; void run(); return()=>{cancelled=true;}; },[router]); return <AppShell title="Analyzing"><div className="mx-auto flex min-h-[calc(100dvh-4rem)] max-w-xl items-center p-5"><section className="w-full"><div className="relative mx-auto mb-10 grid size-28 place-items-center"><div className="absolute inset-0 animate-pulse rounded-full bg-emerald-400/10" /><div className="size-14 rounded-full border-2 border-emerald-300 border-t-transparent animate-spin" /><span className="absolute font-mono text-sm text-emerald-200">{Math.round(((active+1)/stages.length)*100)}%</span></div><h1 className="text-center text-3xl font-semibold tracking-tight">Building your comparison.</h1><p className="mt-3 text-center text-sm text-zinc-500">The score and safety review are deterministic. AI only writes the summary.</p>{error ? <div className="mt-8 rounded-2xl border border-red-400/25 bg-red-400/10 p-4 text-sm text-red-200">{error}</div> : <div className="glass-panel mt-8 rounded-3xl p-5">{stages.map((stage,index)=><div key={stage} className={`flex items-center gap-3 py-3 text-sm ${index>active?"text-zinc-600":"text-zinc-200"}`}><span className={`grid size-6 place-items-center rounded-full border ${index<active?"border-emerald-400 bg-emerald-400 text-zinc-950":index===active?"border-emerald-400 text-emerald-300":"border-white/10"}`}>{index<active?<Check className="size-3"/>:<span className="text-[10px]">{index+1}</span>}</span>{stage}</div>)}</div>}</section></div></AppShell>; }
