import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Camera, ChartNoAxesCombined, LockKeyhole } from "lucide-react";
import BlurText from "@/components/BlurText";

export default function Home() {
  return <main className="min-h-[100dvh] overflow-hidden">
    <nav className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-2 font-semibold"><span className="grid size-8 place-items-center rounded-xl bg-emerald-400 text-zinc-950">F</span>Folliq</Link><div className="flex items-center gap-2"><Link href="/demo" className="hidden px-3 py-2 text-sm text-zinc-400 hover:text-white sm:block">View demo</Link><Link href="/onboarding" className="rounded-full bg-white px-4 py-2 text-sm font-semibold text-zinc-950">Get started</Link></div></nav>
    <section className="mx-auto grid min-h-[calc(100dvh-4rem)] max-w-7xl items-center gap-10 px-5 py-10 md:grid-cols-[0.85fr_1.15fr] md:py-14">
      <div className="relative z-10"><p className="mb-5 text-sm font-medium text-emerald-300">See your routine more clearly</p><BlurText text="Progress you can follow, one consistent photo at a time." delay={65} animateBy="words" direction="top" className="max-w-[12ch] text-4xl font-semibold leading-[1.02] tracking-[-0.05em] sm:text-5xl lg:text-6xl" /><p className="mt-6 max-w-md text-base leading-7 text-zinc-400">Guided scalp check-ins compare your progress with your own baseline. Private, explainable, and never diagnostic.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/onboarding" className="inline-flex items-center gap-2 rounded-full bg-emerald-400 px-5 py-3 font-semibold text-zinc-950 transition hover:bg-emerald-300 active:scale-[0.98]">Start your baseline <ArrowRight className="size-4" /></Link><Link href="/dashboard" className="rounded-full border border-white/12 px-5 py-3 font-medium text-white hover:bg-white/5">Explore the demo</Link></div></div>
      <div className="glass-panel relative min-h-[420px] overflow-hidden rounded-3xl md:min-h-[600px]"><Image src="/folliq-hero.png" alt="Abstract visualization of consistent scalp progress photos" fill priority className="object-cover object-[64%_center]" sizes="(max-width: 768px) 100vw, 58vw" /><div className="absolute inset-0 bg-gradient-to-t from-zinc-950/70 via-transparent to-transparent" /><div className="glass-panel absolute inset-x-4 bottom-4 rounded-2xl p-4 sm:inset-x-auto sm:bottom-6 sm:left-6 sm:w-64"><div className="flex items-end justify-between"><div><p className="text-xs text-zinc-400">Relative score</p><p className="text-3xl font-semibold tracking-tight">116.8</p></div><span className="text-sm font-medium text-emerald-300">+16.8%</span></div><p className="mt-2 text-xs leading-5 text-zinc-400">Example demo data, compared with a personal baseline of 100.</p></div></div>
    </section>
    <section className="mx-auto max-w-7xl px-5 py-20"><h2 className="max-w-lg text-3xl font-semibold tracking-tight">A focused loop that gets more useful over time.</h2><div className="mt-10 grid gap-8 border-t border-white/10 pt-8 md:grid-cols-[1.15fr_0.85fr_1fr]">{[[Camera,"Capture consistently","A guided frame checks lighting and sharpness before each photo."],[ChartNoAxesCombined,"Compare your baseline","Scores are relative to your first usable scan, never an absolute density claim."],[LockKeyhole,"Keep it private","Photos stay user-scoped. Location metadata is removed before upload."]].map(([Icon,title,copy]) => { const I = Icon as typeof Camera; return <article key={String(title)}><I className="size-5 text-emerald-300" /><h3 className="mt-4 font-medium">{String(title)}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-zinc-500">{String(copy)}</p></article>; })}</div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-3 border-t border-white/10 px-5 py-8 text-xs leading-5 text-zinc-600 sm:flex-row sm:items-center sm:justify-between"><p>Folliq is an educational progress tool, not a medical or diagnostic product.</p><Link href="/settings" className="text-zinc-400 hover:text-white">Privacy and data controls</Link></footer>
  </main>;
}
