"use client";
/* Captured data URLs are local previews and cannot use Next image optimization. */
/* eslint-disable @next/next/no-img-element */

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Camera, Check, RotateCcw, ShieldX, Sun, ScanLine } from "lucide-react";
import { Button } from "@/components/ui/button";

type CameraState = "loading" | "ready" | "denied" | "unsupported" | "captured";

export function CameraCapture() {
  const videoRef = useRef<HTMLVideoElement>(null); const canvasRef = useRef<HTMLCanvasElement>(null); const streamRef = useRef<MediaStream | null>(null);
  const [state,setState] = useState<CameraState>("loading"); const [preview,setPreview] = useState<string | null>(null); const [count,setCount] = useState<number | null>(null); const router = useRouter();
  const stop = useCallback(() => { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; },[]);
  const start = useCallback(async () => { if (!navigator.mediaDevices?.getUserMedia) { setState("unsupported"); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment", width: { ideal: 1280 }, height: { ideal: 1280 } }, audio: false }); streamRef.current = stream; if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); } setState("ready"); } catch { setState("denied"); } },[]);
  useEffect(() => { queueMicrotask(() => void start()); return stop; },[start,stop]);
  const snap = () => { if (!videoRef.current || !canvasRef.current) return; const video=videoRef.current, canvas=canvasRef.current; const size=Math.min(video.videoWidth, video.videoHeight); canvas.width=900; canvas.height=900; const x=(video.videoWidth-size)/2, y=(video.videoHeight-size)/2; canvas.getContext("2d")?.drawImage(video,x,y,size,size,0,0,900,900); const image=canvas.toDataURL("image/webp",0.78); setPreview(image); sessionStorage.setItem("folliq-capture",image); setState("captured"); stop(); };
  const countdown = () => { let value=3; setCount(value); const timer=setInterval(() => { value -= 1; if(value === 0){ clearInterval(timer); setCount(null); snap(); } else setCount(value); },700); };
  const retake = () => { setPreview(null); setState("loading"); void start(); };
  if (state === "denied" || state === "unsupported") return <div className="flex min-h-[calc(100dvh-4rem)] items-center justify-center p-5"><div className="glass-panel max-w-md rounded-3xl p-7 text-center"><ShieldX className="mx-auto size-8 text-amber-300" /><h2 className="mt-5 text-2xl font-medium">{state === "denied" ? "Camera access is blocked" : "Camera is not available"}</h2><p className="mt-3 text-sm leading-6 text-zinc-400">{state === "denied" ? "Allow camera access in your browser settings, then try again. You stay in control of when a photo is captured." : "Use a modern browser with camera support, or continue with a demo capture."}</p><Button className="mt-6" onClick={() => { sessionStorage.removeItem("folliq-capture"); router.push("/check-in/questionnaire"); }}>Use demo capture</Button></div></div>;
  return <div className="relative min-h-[calc(100dvh-4rem)] overflow-hidden bg-zinc-950"><video ref={videoRef} playsInline muted className={`absolute inset-0 size-full object-cover ${state === "captured" ? "hidden" : ""}`} /><canvas ref={canvasRef} className="hidden" />{preview && <img src={preview} alt="Captured scalp preview" className="absolute inset-0 size-full object-cover" />}
    <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_38%_30%_at_50%_43%,transparent_0%,transparent_75%,rgba(9,9,11,.78)_76%)]" /><div className="pointer-events-none absolute left-1/2 top-[43%] h-[30%] w-[38%] -translate-x-1/2 -translate-y-1/2 rounded-[50%] border-2 border-emerald-300/80 shadow-[0_0_0_1px_rgba(0,0,0,.35)]"><span className="absolute left-1/2 top-0 h-3 w-px -translate-x-1/2 bg-emerald-300" /><span className="absolute bottom-0 left-1/2 h-3 w-px -translate-x-1/2 bg-emerald-300" /></div>{count && <div className="absolute inset-0 grid place-items-center bg-zinc-950/35 text-7xl font-semibold backdrop-blur-sm">{count}</div>}
    <div className="absolute inset-x-0 top-0 flex items-center justify-between p-4"><div className="glass-panel rounded-full px-3 py-2 text-xs">Align the crown inside the guide</div><div className="glass-panel flex items-center gap-2 rounded-full px-3 py-2 text-xs text-emerald-200"><Check className="size-3" />Stable</div></div>
    <div className="absolute inset-x-0 bottom-0 p-4 pb-8"><div className="mx-auto mb-5 flex max-w-sm justify-center gap-2"><span className="glass-panel flex items-center gap-2 rounded-full px-3 py-2 text-xs"><Sun className="size-3 text-emerald-300" />Lighting good</span><span className="glass-panel flex items-center gap-2 rounded-full px-3 py-2 text-xs"><ScanLine className="size-3 text-emerald-300" />Guide aligned</span></div>{state === "captured" ? <div className="mx-auto flex max-w-sm gap-3"><Button variant="secondary" className="h-12 flex-1" onClick={retake}><RotateCcw />Retake</Button><Button className="h-12 flex-1" onClick={() => router.push("/check-in/questionnaire")}>Use photo<Check /></Button></div> : <button disabled={state !== "ready"} onClick={countdown} aria-label="Capture photo" className="mx-auto grid size-20 place-items-center rounded-full border-4 border-white bg-white/20 transition active:scale-95 disabled:opacity-40"><span className="grid size-14 place-items-center rounded-full bg-white text-zinc-950"><Camera className="size-6" /></span></button>}</div>
  </div>;
}
